In [49]:
## import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [50]:
## load the dataset
df = pd.read_csv('emails.csv')
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB


In [52]:
df = df.drop(columns=['Email No.'])


In [53]:
df

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  \
0       0   0    1    0    0   0    2    0    0   0  ...         0    0   
1       8  13   24    6    6   2  102    1   27  18  ...         0    0   
2       0   0    1    0    0   0    8    0    0   4  ...         0    0   
3       0   5   22    0    5   1   51    2   10   1  ...         0    0   
4       7   6   17    1    5   2   57    0    9   3  ...         0    0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
5167    2   2    2    3    0   0   32    0    0   5  ...         0    0   
5168   35  27   11    2    6   5  151    4    3  23  ...         0    0   
5169    0   0    1    1    0   0   11    0    0   1  ...         0    0   
5170    2   7    1    0    2   1   28    2    0   8  ...         0    0   
5171   22  24    5    1    6   5  148    8    2  23  ...         0    0   

      valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0          0    0               0         0         0   0    0           0  
1          0    0               0         0         0   1    0           0  
2          0    0               0         0         0   0    0           0  
3          0    0               0         0         0   0    0           0  
4          0    0               0         0         0   1    0           0  
...      ...  ...             ...       ...       ...  ..  ...         ...  
5167       0    0               0         0         0   0    0           0  
5168       0    0               0         0         0   1    0           0  
5169       0    0               0         0         0   0    0           1  
5170       0    0               0         0         0   1    0           1  
5171       0    0               0         0         0   0    0           0  

[5172 rows x 3001 columns]

In [54]:
## regex , regular expression
df = df.replace(to_replace = r'[^a - zA -Z]', value=float('nan'),regex=True)
df.fillna(0, inplace=True)

##convert into integer type
df = df.astype(int)


In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3001 entries, the to Prediction
dtypes: int32(3001)
memory usage: 59.2 MB


In [56]:
# split the data into independent and dependent variable    ##classsification
from sklearn.model_selection import train_test_split
X = df.iloc[:, :-1].values  ##  same as X = df.iloc[:, 0:3002].values
y = df.iloc[:, -1].values

In [57]:
## split the data into trainig and testing set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 32)



In [58]:
## train the logistic regression
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train, y_train)

c:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [59]:
## make the prediction
pred_LR = model_LR.predict(X_test) 
pd.DataFrame({'Actual': y_test, 'Prediction': pred_LR})

Actual  Prediction
0          0           1
1          0           0
2          0           0
3          0           0
4          1           1
...      ...         ...
1030       1           1
1031       0           0
1032       1           1
1033       0           0
1034       1           1

[1035 rows x 2 columns]

In [60]:
## evaluate the model accuracy
from sklearn.metrics import accuracy_score
accuracy_LR =accuracy_score(y_test, pred_LR)

## confusion metrics
from sklearn.metrics import accuracy_score, confusion_matrix
conf_mat = confusion_matrix(y_test, pred_LR)
print(accuracy_LR)
print(conf_mat)

0.9594202898550724
[[696  20]
 [ 22 297]]


In [61]:
# naive bayes
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(X_train, y_train)

GaussianNB()

In [62]:
#predit the test set
y_pred_NB = model_NB.predict(X_test)
pd.DataFrame({'Actual': y_test, 'Prediction': y_pred_NB})

Actual  Prediction
0          0           0
1          0           0
2          0           0
3          0           0
4          1           1
...      ...         ...
1030       1           1
1031       0           0
1032       1           1
1033       0           0
1034       1           1

[1035 rows x 2 columns]

In [63]:
accuracy_NB = accuracy_score(y_test,y_pred_NB)
conf_mat_NB = confusion_matrix(y_test,y_pred_NB)
print(accuracy_NB)
print(conf_mat_NB)

0.9458937198067633
[[676  40]
 [ 16 303]]


In [64]:
## K-Nearest Neigtboors
from sklearn.neighbors import KNeighborsClassifier
Knn_model = KNeighborsClassifier(n_neighbors=5)
##trainin the model
Knn_model.fit(X_train,y_train)



KNeighborsClassifier()

In [65]:
## make the prediction
pred_Kn = Knn_model.predict(X_test) 
pd.DataFrame({'Actual': y_test, 'Prediction': pred_Kn})

Actual  Prediction
0          0           1
1          0           0
2          0           0
3          0           0
4          1           1
...      ...         ...
1030       1           1
1031       0           0
1032       1           1
1033       0           0
1034       1           1

[1035 rows x 2 columns]

In [66]:
accuracy_knn = accuracy_score(y_test,pred_Kn)
conf_mat_knn = confusion_matrix(y_test,pred_Kn)
print(accuracy_knn)
print(conf_mat_knn)

0.8734299516908213
[[631  85]
 [ 46 273]]


In [80]:
## Desition Tree classifier
from sklearn.tree import DecisionTreeClassifier
Decision_tree_gini = DecisionTreeClassifier(criterion='gini',random_state=100, max_depth=3,min_samples_leaf=5)
Decision_tree_max_depth = DecisionTreeClassifier(max_depth=5)
Decision_tree_entropy = DecisionTreeClassifier(criterion='entropy',random_state=100,max_depth=3,min_samples_leaf=5)



In [81]:
##training the models
Decision_tree_gini.fit(X_train,y_train)
Decision_tree_max_depth.fit(X_train,y_train)
Decision_tree_entropy.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [82]:
## make predictions
y_pred_gini = Decision_tree_gini.predict(X_test) 
y_pred_max_Dept = Decision_tree_max_depth.predict(X_test) 
y_pred_entropy = Decision_tree_entropy.predict(X_test) 

In [83]:
pd.DataFrame({'Actual': y_test, 'Prediction': y_pred_gini})


Actual  Prediction
0          0           1
1          0           0
2          0           0
3          0           0
4          1           1
...      ...         ...
1030       1           1
1031       0           0
1032       1           1
1033       0           0
1034       1           1

[1035 rows x 2 columns]

In [84]:
##evaluate the gini
accuracy_gini = accuracy_score(y_test,y_pred_gini)
conf_mat_gini = confusion_matrix(y_test,y_pred_gini)
print(accuracy_gini)
print(conf_mat_gini)

0.8347826086956521
[[690  26]
 [145 174]]


In [85]:
pd.DataFrame({'Actual': y_test, 'Prediction': y_pred_max_Dept})

Actual  Prediction
0          0           1
1          0           0
2          0           0
3          0           0
4          1           1
...      ...         ...
1030       1           1
1031       0           0
1032       1           1
1033       0           0
1034       1           1

[1035 rows x 2 columns]

In [86]:
##evaluate the max_Dept
accuracy_max_Dept = accuracy_score(y_test,y_pred_max_Dept)
conf_mat_max_Dept = confusion_matrix(y_test,y_pred_max_Dept)
print(accuracy_max_Dept)
print(conf_mat_max_Dept)

0.8444444444444444
[[703  13]
 [148 171]]


In [87]:
pd.DataFrame({'Actual': y_test, 'Prediction': y_pred_entropy})

Actual  Prediction
0          0           1
1          0           0
2          0           0
3          0           0
4          1           1
...      ...         ...
1030       1           1
1031       0           1
1032       1           1
1033       0           0
1034       1           1

[1035 rows x 2 columns]

In [88]:
##evaluate the entropy
accuracy_entropy = accuracy_score(y_test,y_pred_entropy)
conf_mat_entropy = confusion_matrix(y_test,y_pred_entropy)
print(accuracy_entropy)
print(conf_mat_entropy)

0.7855072463768116
[[497 219]
 [  3 316]]
